formatter: "markdown table" # this is required

version: ""

header-from: main.tf
footer-from: ""

recursive:
  enabled: false
  path: modules

sections:
  hide: []
  show: []

content: |-
# .terraform-docs.yml
content: |-
  {{ .Header }}

  {{ .Footer }}

  {{ .Providers }}

  {{ .Requirements }}

  {{ .Inputs }}

  {{ .Resources }}

  ## Example

  Check the [examples](examples/) folder for a complete example of how to use this module.

  ### 3 nic CitrixADC

  ```hcl
  {{ include "examples/simple_3nic_citrixadc/main.tf" }}
  ```

  ### 3 nic CitrixADC with Pooled License
  ```hcl
  {{ include "examples/simple_3nic_citrixadc_with_pooled_license/main.tf" }}
  ```
  {{ .Outputs }}
output:
  file: ""
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: required

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true